name: tiki_sdk_flutter_plugin
description: Flutter plugin to expose TIKI SDK native code to Android and iOS
version: 0.0.2
homepage: https://github.com/tiki/tiki-sdk-flutter/tiki_sdk_flutter_plugin

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mytiki.tiki_sdk_flutter_plugin
        pluginClass: TikiSdkFlutterChannel
      ios:
        pluginClass: TikiSdkFlutterChannel

