name: tiki_sdk_flutter
description: The TIKI SDK implementation for Flutter. Create data Ownership and Consent NFTs with TIKI.
version: 0.0.5
homepage: https://github.com/tiki/tiki-sdk-flutter/tiki_sdk_flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.1.3
  sqlite3: ^1.9.0
  sqlite3_flutter_libs: ^0.5.10
  tiki_sdk_dart: ^0.0.7
  tiki_sdk_flutter_plugin: ^0.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  module:
    androidX: true
    androidPackage: com.mytiki.tiki_sdk_flutter
    iosBundleIdentifier: com.mytiki.tikiSdkFlutter
